[package]
name = "federatz"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
ureq = {version = "*", features = ["json", "native-certs", "gzip"]}
